// Generated by CoffeeScript 1.4.0
(function() {
  var FeatureSlider,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  FeatureSlider = (function() {

    FeatureSlider.prototype.idx = 0;

    function FeatureSlider(opts) {
      if (opts == null) {
        opts = {};
      }
      this.cycleImages = __bind(this.cycleImages, this);

      if ($('#feature_slider').size() <= 0) {
        return;
      }
      this.$feature_slider = $('#feature_slider');
      this.$features = this.$feature_slider.find('li');
      this.$main_feature = this.$feature_slider.find('#main_feature');
      this.count = this.$features.size();
      this.interval = opts.interval || 5000;
      this.startTimer();
    }

    FeatureSlider.prototype.cycleImages = function() {
      var $current_feature, caption, image;
      if (this.idx === this.count - 1) {
        this.idx = 0;
      } else {
        this.idx++;
      }
      this.$features.removeClass('current');
      $current_feature = $(this.$features[this.idx]);
      $current_feature.addClass('current');
      caption = $current_feature.find('figcaption').html();
      image = $current_feature.find('img').data('large');
      this.$main_feature.find('img').attr('src', image);
      return this.$main_feature.find('figcaption').html(caption);
    };

    FeatureSlider.prototype.startTimer = function() {
      return setInterval(this.cycleImages, this.interval);
    };

    return FeatureSlider;

  })();

  $(function() {
    return new FeatureSlider({
      interval: 3500
    });
  });

}).call(this);
